vim.keymap.set('n','<leader>gs','<cmd>Git status<cr>')
vim.keymap.set('n','<leader>gt','<cmd>Git tree<cr>')
vim.keymap.set('n','<leader>ga','<cmd>Git add %<cr>')
vim.keymap.set('n','<leader>gc','<cmd>Git commit -v %<cr>')
vim.keymap.set('n','<leader>go','<cmd>Git checkout<cr>')
vim.keymap.set('n','<leader>gm','<cmd>Git merge<cr>')
vim.keymap.set('n','<leader>gb','<cmd>Git branch<cr>')
