vim.api.nvim_buf_set_keymap(0,'n', '<leader>aa', ':ArduinoAttach<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>av', ':ArduinoVerify<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>au', ':ArduinoUpload<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>aus', ':ArduinoUploadAndSerial<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>as', ':ArduinoSerial<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>ab', ':ArduinoChooseBoard<CR>', { noremap = true })
vim.api.nvim_buf_set_keymap(0,'n', '<leader>ap', ':ArduinoChooseProgrammer<CR>', { noremap = true })
